"""empty message

Revision ID: 099d24ed2c91
Revises: None
Create Date: 2016-03-05 02:30:49.882000

"""

# revision identifiers, used by Alembic.
revision = '099d24ed2c91'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('urls')
    ### end Alembic commands ###
