"""empty message

Revision ID: 9ddd05fdfeae
Revises: c15f09aecd69
Create Date: 2016-03-05 04:12:50.112241

"""

# revision identifiers, used by Alembic.
revision = '9ddd05fdfeae'
down_revision = 'c15f09aecd69'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'urls', ['url_shortened'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'urls', type_='unique')
    ### end Alembic commands ###
