"""empty message

Revision ID: c15f09aecd69
Revises: da31adc8c80b
Create Date: 2016-03-05 03:15:15.259902

"""

# revision identifiers, used by Alembic.
revision = 'c15f09aecd69'
down_revision = 'da31adc8c80b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'urls', ['url'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'urls', type_='unique')
    ### end Alembic commands ###
